name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip autoconf libtool \
            pkg-config zlib1g-dev libncurses5-dev \
            libncursesw5-dev libtinfo5 cmake \
            libffi-dev libssl-dev

      - name: Install Buildozer with user scope
        run: |
          python -m pip install --user buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Initialize Buildozer
        run: |
          ~/.local/bin/buildozer init
          ~/.local/bin/buildozer android update

      - name: Build APK
        run: |
          ~/.local/bin/buildozer android clean
          ~/.local/bin/buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
