name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Setup Android SDK
        run: |
          mkdir -p ~/.android
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
          touch ~/.android/repositories.cfg
          
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip -d cmdline-tools-temp
          
          find cmdline-tools-temp -name 'sdkmanager' -exec dirname {} \; | xargs -I{} mv {} ~/.buildozer/android/platform/android-sdk/cmdline-tools
          
          mkdir -p ~/.android/licenses
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ~/.android/licenses/android-sdk-license
          
          rm -rf cmdline-tools-temp commandlinetools-linux-*.zip

      - name: Install Buildozer
        run: pip install buildozer

      - name: Build APK
        run: |
          buildozer android clean
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
