name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk \
            wget \
            unzip \
            git \
            zip \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Setup Android SDK
        run: |
          # Create directory structure
          mkdir -p ~/.android
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          touch ~/.android/repositories.cfg
          
          # Download and extract Command Line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip -d cmdline-tools-temp
          
          # Move files to correct location
          mv cmdline-tools-temp/cmdline-tools/* ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/
          
          # Set environment variables
          echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          
          # Accept licenses
          mkdir -p ~/.android/licenses
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ~/.android/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > ~/.android/licenses/android-sdk-preview-license
          
          # Install Android components
          echo "Installing Android packages..."
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-31" "build-tools;31.0.0" "platform-tools" --verbose
          
          # Clean up
          rm -rf cmdline-tools-temp commandlinetools-linux-*.zip

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --user buildozer cython==0.29.33 virtualenv
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
          # Only initialize if buildozer.spec doesn't exist
          if [ ! -f buildozer.spec ]; then
            ~/.local/bin/buildozer init
          else
            echo "buildozer.spec already exists, skipping init"
          fi

      - name: Install python-for-android
        run: |
          # Create directory if not exists
          mkdir -p ~/.buildozer/android/platform/python-for-android
          
          # Clone python-for-android if directory is empty
          if [ -z "$(ls -A ~/.buildozer/android/platform/python-for-android)" ]; then
            git clone https://github.com/kivy/python-for-android.git ~/.buildozer/android/platform/python-for-android
            cd ~/.buildozer/android/platform/python-for-android
            git checkout master
            pip install -e .
          else
            echo "python-for-android already exists, skipping clone"
          fi

      - name: Verify environment
        run: |
          echo "Checking installed components..."
          ~/.local/bin/buildozer --version
          java -version
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --list
          ls -la ~/.buildozer/android/platform/python-for-android

      - name: Build APK
        run: |
          ~/.local/bin/buildozer android clean
          ~/.local/bin/buildozer -v android debug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
